#Local database connection

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7gsvjd8nd3s73e8qprg-a.oregon-postgres.render.com/webshop_di7a
spring.datasource.username=veebipood_user
spring.datasource.password=Hxc7qhTON539w0zt7pmPlTNQBKcmc3H2